[package]
name = "dcbothub"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.9"
url = "2.3.1"
git2 = "0.15.0"